version: "2.1"

services:
  tuleap:
    image: enalean/tuleap-aio
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      DB_HOST: "db"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - tuleap-data:/data
    ports:
      - 1080:80
      - 10443:443
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - tuleap-db-data:/var/lib/mysql
      - ./sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

volumes:
  tuleap-db-data:
  tuleap-data:
