version: "3"

services:
  tuleap:
    image: enalean/tuleap-aio
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      DB_HOST: "db"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - tuleap-data:/data
    networks:
      - proxy
      - default    
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.serviceDomain=tuleap.app.lucaguzzon.com
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - tuleap-db-data:/var/lib/mysql
      - ./sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default
      
volumes:
  tuleap-db-data:
  tuleap-data:

networks:
  default:
    external: false
  proxy:
    external: true
